### ISSUE TITLE
Invalid handle error when using Colab page

### ISSUE THREAD

**Issue by jastrayy** [kanjieater/AudiobookTextSync#18]
Great tool and I've used it to transcribe a few videos already. When following the same steps to generate subs today, I'm getting this error:

```
Transcribing...
Detected Language: japanese
Transcribing with faster-whisper (large-v3)...
Transcribe:   0% 0/13038.21 [00:00<?, ?sec/s]Unable to load any of {libcudnn_ops.so.9.1.0, libcudnn_ops.so.9.1, libcudnn_ops.so.9, libcudnn_ops.so}
Invalid handle. Cannot load symbol cudnnCreateTensorDescriptor
```

**Comment by kanjieater** [comment]
Try `!pip install ctranslate2==4.4.0`

People have been running into this recently with whisper related projects, and I'm not really sure why. This fixed it for people in TheMoeWay SubPlz thread linked in the readme

Source:
https://github.com/SYSTRAN/faster-whisper/issues/1086

**Comment by jastrayy** [comment]
Thank you! Adding that line helped to get it working again.
