### ISSUE TITLE
IndexError('list index out of range')

### ISSUE THREAD

**Issue by Tenome** [kanjieater/AudiobookTextSync#2]
I'm trying this out for the first time, and I've encountered this error while saving the VTT file. I'm not sure what's causing it, but it seems to be an issue with Python. It's probably my fault somehow but I have no idea what it could be.

`
C:\Users\ \Desktop\AudiobookTextSync-master>python run.py -d "E:\Books\とある飛空士への追憶"
Working on E:\Books\とある飛空士への追憶\
Splitting script into sentences
100%|████████████████████████████████████████████████████████████████████████████| 6286/6286 [00:01<00:00, 3484.25it/s]
'1 file will be processed:'
['E:\\Books\\とある飛空士への追憶\\とある飛空士への追憶（ガガガ文庫） （小学館）.m4b']
100%|███████████████████████████████████████████████████████████████████████████████████| 1/1 [07:10<00:00, 430.95s/it]
  0%|                                                                                                             | 0/1 [00:00<?, ?it/s]C:\Users\ \AppData\Local\Programs\Python\Python39\lib\site-packages\stable_whisper\whisper_word_level.py:190: UserWarning: FP16 is not supported on CPU; using FP32 instead
  warnings.warn("FP16 is not supported on CPU; using FP32 instead")
Predicted silence(s) with VAD
100%|████████████████████████████████████████████████████████████████████████████████████| 31865.77/31865.77 [1:14:25<00:00,  7.14sec/s]
Saved: E:\Books\とある飛空士への追憶\とある飛空士への追憶（ガガガ文庫） （小学館）.filtered.ass5.77/31865.77 [1:14:25<00:00,  3.21sec/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [1:40:01<00:00, 6001.90s/it]
とある飛空士への追憶.vtt
IndexError('list index out of range')
The following 1 failed:
'E:\\Books\\とある飛空士への追憶\\'
IndexError('list index out of range')`

The resulting vtt file got about 8 minutes in.

System:
Windows 10 (wsl2 installed)
Python 3.9.9

**Comment by Tenome** [comment]
Right as I joined the LearnJapanese discord, I found out the issue since someone else had the same problem. Posting here in case anyone comes across it.

_Folder name and audio file have to match. txt file can be named anything, but might as well name it the same._

**Comment by kanjieater** [comment]
I'll add a better error message when I get a chance - thanks for the report. 

What discord server are you referring to @Tenome? The only discord server with active discussions around the tool to my knowledge is https://learnjapanese.moe/join/
